// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using mmangold.com;
using System;

namespace mmangold.com.Migrations
{
    [DbContext(typeof(SiteDbContext))]
    [Migration("20190915031645_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("mmangold.com.Models.GuruOrGreaterKanji", b =>
                {
                    b.Property<string>("Character")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("UnlockedDate");

                    b.HasKey("Character");

                    b.HasIndex("Character")
                        .IsUnique();

                    b.ToTable("GuruOrGreaterKanjis");
                });

            modelBuilder.Entity("mmangold.com.Models.GuruOrGreaterRadical", b =>
                {
                    b.Property<string>("ImageUri")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("UnlockedDate");

                    b.HasKey("ImageUri");

                    b.HasIndex("ImageUri")
                        .IsUnique();

                    b.ToTable("GuruOrGreaterRadicals");
                });

            modelBuilder.Entity("mmangold.com.Models.GuruOrGreaterVocab", b =>
                {
                    b.Property<string>("Character")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("UnlockedDate");

                    b.HasKey("Character");

                    b.HasIndex("Character")
                        .IsUnique();

                    b.ToTable("GuruOrGreaterVocabs");
                });

            modelBuilder.Entity("mmangold.com.Models.LevelProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDateTime");

                    b.Property<string>("Level");

                    b.HasKey("Id");

                    b.ToTable("LevelProgresses");
                });

            modelBuilder.Entity("mmangold.com.Models.SimpleWeightLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<int>("DayOfYear");

                    b.Property<float>("Weight");

                    b.HasKey("Id");

                    b.ToTable("SimpleWeightLogs");
                });

            modelBuilder.Entity("mmangold.com.Models.WaniKaniSync", b =>
                {
                    b.Property<int>("WaniKaniSyncId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("SyncDate");

                    b.HasKey("WaniKaniSyncId");

                    b.ToTable("WaniKaniSyncs");
                });

            modelBuilder.Entity("mmangold.com.Models.WeightSync", b =>
                {
                    b.Property<int>("WeightSyncId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("NewRecords");

                    b.Property<DateTime>("SyncDate");

                    b.HasKey("WeightSyncId");

                    b.ToTable("WeightSyncs");
                });
#pragma warning restore 612, 618
        }
    }
}
